url: "https://spaghetti-lover.github.io"
baseurl: ""
collections:
  sections:
    output: false
  projects:
    output: false
  news:
    output: false
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
